//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibraryP.ShopfloorPKG.Localization {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShopfloorLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShopfloorLanguage() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibraryP.ShopfloorPKG.Localization.ShopfloorLanguage", typeof(ShopfloorLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Item Record 的當地語系化字串。
        /// </summary>
        public static string Item_Record {
            get {
                return ResourceManager.GetString("Item Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lot 的當地語系化字串。
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ng 的當地語系化字串。
        /// </summary>
        public static string Ng {
            get {
                return ResourceManager.GetString("Ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ok 的當地語系化字串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Process 的當地語系化字串。
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serial no 的當地語系化字串。
        /// </summary>
        public static string Serial_no {
            get {
                return ResourceManager.GetString("Serial no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start time 的當地語系化字串。
        /// </summary>
        public static string Start_time {
            get {
                return ResourceManager.GetString("Start time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station 的當地語系化字串。
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station In 的當地語系化字串。
        /// </summary>
        public static string Station_In {
            get {
                return ResourceManager.GetString("Station In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station Out 的當地語系化字串。
        /// </summary>
        public static string Station_Out {
            get {
                return ResourceManager.GetString("Station Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stations Status 的當地語系化字串。
        /// </summary>
        public static string Stations_Status {
            get {
                return ResourceManager.GetString("Stations Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workorder Deploy 的當地語系化字串。
        /// </summary>
        public static string Workorder_Deploy {
            get {
                return ResourceManager.GetString("Workorder Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workorder no 的當地語系化字串。
        /// </summary>
        public static string Workorder_No {
            get {
                return ResourceManager.GetString("Workorder No", resourceCulture);
            }
        }
    }
}
