//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibraryP.MapPKG.Localization {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MapLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapLanguage() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibraryP.MapPKG.Localization.MapLanguage", typeof(MapLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Component Info 的當地語系化字串。
        /// </summary>
        public static string Component_Info {
            get {
                return ResourceManager.GetString("Component Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Height 的當地語系化字串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image 的當地語系化字串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image Name 的當地語系化字串。
        /// </summary>
        public static string Image_Name {
            get {
                return ResourceManager.GetString("Image Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image Type 的當地語系化字串。
        /// </summary>
        public static string Image_Type {
            get {
                return ResourceManager.GetString("Image Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map 的當地語系化字串。
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map Name 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Selected Component 的當地語系化字串。
        /// </summary>
        public static string Selected_Component {
            get {
                return ResourceManager.GetString("Selected Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target Machine 的當地語系化字串。
        /// </summary>
        public static string Target_Machine {
            get {
                return ResourceManager.GetString("Target Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target Station 的當地語系化字串。
        /// </summary>
        public static string Target_Station {
            get {
                return ResourceManager.GetString("Target Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Width 的當地語系化字串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 X position 的當地語系化字串。
        /// </summary>
        public static string X_Position {
            get {
                return ResourceManager.GetString("X Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Y position 的當地語系化字串。
        /// </summary>
        public static string Y_Position {
            get {
                return ResourceManager.GetString("Y Position", resourceCulture);
            }
        }
    }
}
