<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Authors>Peter Yuan</Authors>
		<Version>8.0.2</Version>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<EnableDefaultContentItems>true</EnableDefaultContentItems>
		<StaticWebAssetsEnabled>true</StaticWebAssetsEnabled>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="MachinePKG\EFPartialModel\AwaitAction.partial.cs" />
		<Compile Remove="MachinePKG\EFPartialModel\Condition.partial.cs" />
		<Compile Remove="MachinePKG\EFPartialModel\ConditionAction.partial.cs" />
		<Compile Remove="MachinePKG\EFPartialModel\ConditionConstDataNode.partial.cs" />
		<Compile Remove="MachinePKG\EFPartialModel\ConditionLogicNode.partial.cs" />
		<Compile Remove="MachinePKG\EFPartialModel\ConditionNode.partial.cs" />
		<Compile Remove="MachinePKG\EFPartialModel\ConditionTagDataNode.partial.cs" />
		<Compile Remove="MachinePKG\EFPartialModel\SetTagAction.partial.cs" />
		<Compile Remove="MachinePKG\Extension\MachineRouteAttribute.cs" />
		<Compile Remove="MachinePKG\Extension\MachineRouteRegistry.cs" />
		<Compile Remove="MapPKG\Component\Setting\MapComponent\MapEditComponentBase.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\ItemRecordConfig.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\ItemRecordContent.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\ItemRecordDetail.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\RecipeItem.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\TaskRecordConfig.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\TaskRecordContent.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\TaskRecordDetail.cs" />
		<Compile Remove="ShopfloorPKG\EFModel\WorkorderRecipeConfig.cs" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="MachinePKG\Component\Setting\ConditionSetting.razor" />
		<Content Remove="MapPKG\Component\Setting\MapComponent\MapComponentEdit.razor" />
	</ItemGroup>

	<ItemGroup>
		<None Include="MachinePKG\EFPartialModel\AwaitAction.partial.cs" />
		<None Include="MachinePKG\EFPartialModel\Condition.partial.cs" />
		<None Include="MachinePKG\EFPartialModel\ConditionAction.partial.cs" />
		<None Include="MachinePKG\EFPartialModel\ConditionConstDataNode.partial.cs" />
		<None Include="MachinePKG\EFPartialModel\ConditionLogicNode.partial.cs" />
		<None Include="MachinePKG\EFPartialModel\ConditionNode.partial.cs" />
		<None Include="MachinePKG\EFPartialModel\ConditionTagDataNode.partial.cs" />
		<None Include="MachinePKG\EFPartialModel\SetTagAction.partial.cs" />
		<None Include="MachinePKG\Extension\MachineRouteAttribute.cs" />
		<None Include="MachinePKG\Extension\MachineRouteRegistry.cs" />
		<None Include="MapPKG\Component\Setting\MapComponent\MapComponentEdit.razor" />
		<None Include="MapPKG\Component\Setting\MapComponent\MapEditComponentBase.cs" />
		<None Include="ShopfloorPKG\EFModel\ItemRecordConfig.cs" />
		<None Include="ShopfloorPKG\EFModel\ItemRecordContent.cs" />
		<None Include="ShopfloorPKG\EFModel\ItemRecordDetail.cs" />
		<None Include="ShopfloorPKG\EFModel\RecipeItem.cs" />
		<None Include="ShopfloorPKG\EFModel\TaskRecordConfig.cs" />
		<None Include="ShopfloorPKG\EFModel\TaskRecordContent.cs" />
		<None Include="ShopfloorPKG\EFModel\TaskRecordDetail.cs" />
		<None Include="ShopfloorPKG\EFModel\WorkorderRecipeConfig.cs" />
	</ItemGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="BitzArt.Blazor.Cookies.Server" Version="1.5.1" />
		<PackageReference Include="DevExpress.Blazor" Version="25.2.7" />
		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="8.0.15" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.15" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.8" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NModbus" Version="3.0.81" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Serilog.Expressions" Version="5.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.2.0" />
		<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1" />
		<PackageReference Include="System.Linq.Async" Version="6.0.3" />
		<PackageReference Include="Z.Blazor.Diagrams" Version="3.0.3" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Localization\CommonLanguage.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>CommonLanguage.resx</DependentUpon>
		</Compile>
		<Compile Update="MachinePKG\Localization\MachineLanguage.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>MachineLanguage.resx</DependentUpon>
		</Compile>
		<Compile Update="MapPKG\Localization\MapLanguage.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>MapLanguage.resx</DependentUpon>
		</Compile>
		<Compile Update="ShopfloorPKG\Localization\ShopfloorLanguage.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ShopfloorLanguage.resx</DependentUpon>
		</Compile>
		<Compile Update="UserPKG\Localization\UserLanguage.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>UserLanguage.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Localization\CommonLanguage.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>CommonLanguage.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="MachinePKG\Localization\MachineLanguage.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>MachineLanguage.Designer.cs</LastGenOutput>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Update="MapPKG\Localization\MapLanguage.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>MapLanguage.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="ShopfloorPKG\Localization\ShopfloorLanguage.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>ShopfloorLanguage.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="UserPKG\Localization\UserLanguage.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>UserLanguage.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="MachinePKG\Controller\" />
		<Folder Include="MapPKG\Component\Setting\MapDashboardComponent\" />
		<Folder Include="ShopfloorPKG\Component\StationComponent\ItemRecordInfo\" />
		<Folder Include="ShopfloorPKG\Component\StationComponent\WorkorderInfo\" />
		<Folder Include="wwwroot\css\" />
		<Folder Include="wwwroot\SVG\MapIcons\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="MachinePKG\Component\Setting\ConditionSetting.razor" />
	</ItemGroup>

</Project>
