//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibraryP.MachinePKG.Localization {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MachineLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MachineLanguage() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibraryP.MachinePKG.Localization.MachineLanguage", typeof(MachineLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection Type 的當地語系化字串。
        /// </summary>
        internal static string Connection_Type {
            get {
                return ResourceManager.GetString("Connection Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data Type 的當地語系化字串。
        /// </summary>
        internal static string Data_Type {
            get {
                return ResourceManager.GetString("Data Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable 的當地語系化字串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input/Output 的當地語系化字串。
        /// </summary>
        internal static string Input_Output {
            get {
                return ResourceManager.GetString("Input/Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IP 的當地語系化字串。
        /// </summary>
        internal static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maximal Retry Count 的當地語系化字串。
        /// </summary>
        internal static string Maximal_Retry_Count {
            get {
                return ResourceManager.GetString("Maximal Retry Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Offset 的當地語系化字串。
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port 的當地語系化字串。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Record Status Changed 的當地語系化字串。
        /// </summary>
        internal static string Record_Status_Changed {
            get {
                return ResourceManager.GetString("Record Status Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Index 的當地語系化字串。
        /// </summary>
        internal static string Start_Index {
            get {
                return ResourceManager.GetString("Start Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station 的當地語系化字串。
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 String Reverse 的當地語系化字串。
        /// </summary>
        internal static string String_Reverse {
            get {
                return ResourceManager.GetString("String Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag Count 的當地語系化字串。
        /// </summary>
        internal static string Tag_Count {
            get {
                return ResourceManager.GetString("Tag Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update By Time 的當地語系化字串。
        /// </summary>
        internal static string Update_By_Time {
            get {
                return ResourceManager.GetString("Update By Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateDelay 的當地語系化字串。
        /// </summary>
        internal static string Update_Delay {
            get {
                return ResourceManager.GetString("Update Delay", resourceCulture);
            }
        }
    }
}
