// <auto-generated />
using System;
using CommonLibraryP.MachinePKG;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonLibraryP.MachinePKG.Migrations
{
    [DbContext(typeof(MachineDBContext))]
    partial class MachineDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonLibraryP.MachinePKG.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("int")
                        .HasColumnName("MaxRetryCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<bool>("RecordStatusChanged")
                        .HasColumnType("bit")
                        .HasColumnName("RecordStatusChanged");

                    b.Property<Guid?>("TagCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TagCategoryID");

                    b.Property<int>("UpdateDelay")
                        .HasColumnType("int")
                        .HasColumnName("UpdateDelay");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TagCategoryId");

                    b.ToTable("Machine", (string)null);
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.MachineStatusLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LogTime");

                    b.Property<Guid>("MachineID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MachineID");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("MachineStatusLogs", (string)null);
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.ModbusSlaveConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ip");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("Port");

                    b.Property<int>("Station")
                        .HasColumnType("int")
                        .HasColumnName("Station");

                    b.HasKey("Id");

                    b.ToTable("ModbusSlaveConfigs", (string)null);
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("UpdateByTime")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.TagCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TagCategory", (string)null);
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.TagWarningCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComparisonCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WarningMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TagId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.ModbusTCPTag", b =>
                {
                    b.HasBaseType("CommonLibraryP.MachinePKG.Tag");

                    b.Property<bool>("InputOrOutput")
                        .HasColumnType("bit");

                    b.Property<int>("Offset")
                        .HasColumnType("int");

                    b.Property<int>("StartIndex")
                        .HasColumnType("int");

                    b.Property<byte>("Station")
                        .HasColumnType("tinyint");

                    b.Property<bool>("StringReverse")
                        .HasColumnType("bit");

                    b.ToTable("ModbusTCPTags");
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.TagWarningBoolCondition", b =>
                {
                    b.HasBaseType("CommonLibraryP.MachinePKG.TagWarningCondition");

                    b.Property<bool>("TargetBoolValue")
                        .HasColumnType("bit");

                    b.ToTable("TagWarningBoolConditions", (string)null);
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.TagWarningUshortCondition", b =>
                {
                    b.HasBaseType("CommonLibraryP.MachinePKG.TagWarningCondition");

                    b.Property<int>("TargetUshortValue")
                        .HasColumnType("int");

                    b.ToTable("TagWarningUshortConditions", (string)null);
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.Machine", b =>
                {
                    b.HasOne("CommonLibraryP.MachinePKG.TagCategory", "TagCategory")
                        .WithMany("Machines")
                        .HasForeignKey("TagCategoryId");

                    b.Navigation("TagCategory");
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.Tag", b =>
                {
                    b.HasOne("CommonLibraryP.MachinePKG.TagCategory", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.TagWarningCondition", b =>
                {
                    b.HasOne("CommonLibraryP.MachinePKG.Tag", "Tag")
                        .WithMany("TagWarningConditions")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.Tag", b =>
                {
                    b.Navigation("TagWarningConditions");
                });

            modelBuilder.Entity("CommonLibraryP.MachinePKG.TagCategory", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
